apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dw9jf62cy-go
  janus-idp.io/tekton: dw9jf62cy-go
  backstage.io/kubernetes-id: dw9jf62cy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dw9jf62cy-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
