apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dw9jf62cy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dw9jf62cy-go 
  name: dw9jf62cy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dw9jf62cy-go 
